### ISSUE TITLE
jx preview fails with a panic: runtime error

### ISSUE THREAD

**Issue by jasoncarreira** [jenkins-x/jenkins-x-platform#1622] opened 2018-06-13 21:28 UTC
I'm getting this error every time I try to create a preview environment to run tests during my builds:

```
[preview] Running shell script
+ jx preview --app keycloak-service -n keycloak-service-develop-97
Creating a preview
WARNING: No GitInfo could be found!Unable to convert PR develop to a number
Created environment keycloak-service-develop-97
expose:
  config:
    domain: k8s.nestup.com
    exposer: ""
    http: ""
    tlsacme: ""
preview:
  image:
    repository: 100.67.27.94:5000/ppi/keycloak-service
    tag: 0.0.0-SNAPSHOT-develop-97
EXITCODE   0WARNING: Could not find the service URL in namespace jx-keycloak-service-develop-97 for names keycloak-service, jx-keycloak-service-develop-97, jx-keycloak-service-develop-97-preview, jx-keycloak-service-develop-97-keycloak-service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1717237]
goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*PreviewOptions).Run(0xc420321180, 0xc4207a9c50, 0x0)
    /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/preview.go:504 +0x1287
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdPreview.func1(0xc420321400, 0xc4207baec0, 0x0, 0x4)
    /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/preview.go:92 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420321400, 0xc4207bae80, 0x4, 0x4, 0xc420321400, 0xc4207bae80)
    /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420090f00, 0xc4207cea00, 0xc42053e280, 0xc420744780)
    /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420090f00, 0xc42073cc80, 0x28b5a40)
    /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4206bbf70, 0x179dfc9)
    /home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
    /home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
script returned exit code 2
```

I basically can't do builds or move forward with implementing JX until this is fixed

**Comment by jstrachan** [comment] 2018-06-14 07:59
its a regression caused by the new bitbucket server code.  Fixed now - should be released today...

**Closed by jstrachan** 2018-06-14 07:59 UTC
