### ISSUE TITLE
garbage collection cronjobs produce massive amounts of error pods

### ISSUE THREAD

**Issue by Marthijs-Berfelo** [jenkins-x/jenkins-x-platform#3158] opened 2018-08-28 19:26 UTC
### Summary 
Every time the cronjobs for garbage collection of previews and activities are triggered they produce a lot of error pods (hundreds in a couple of minutes) and nodes become unusable (NodeNotReady) due to:
```rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194784 vs. 4194304)```

I can get the node back online by stopping kubelet, removing all error containers, restarting docker and starting kubelet back up. 

For now I have removed the cronjobs from the cluster, but I would rather find the root cause for the job error and fix it. However I don't know how to properly debug the problem, kubectl logs for the error pods does not provide any clue.

Please help.

### Jx version

| NAME | VERSION |
|---|---|
| jx | 1.3.190 |
| jenkins x platform | 0.0.2252 |
| kubernetes cluster | v1.10.3 |
| kubectl | v1.11.2 |
| helm client | v2.10.0+g9ad53aa |
| helm server | v2.10.0+g9ad53aa |
| git | git version 2.18.0 |

### Kubernetes cluster
3 nodes 1 master on AWS created with KOPS (Version 1.10.0 (git-8b52ea6d1))

**Comment by tallaxes** [comment] 2018-08-31 20:34
Ran into the same problem. In my case the root cause was that gc jobs were trying to connect to jx using the external FQDN, not accessible within the (on-prem) cluster. Investigating further ...

**Comment by tallaxes** [comment] 2018-08-31 21:01
Ok, it looks like at least the uncontrolled growth in number of pods is due to  https://github.com/kubernetes/kubernetes/issues/62382, fixed in 1.10.5 (and 1.11); temporary workaround is to set `activeDeadlineSeconds` on job template.

**Comment by ThomasThiemann** [comment] 2018-11-20 08:14
Hi Tallaxes!
Did you try this temporary workaround? Did it help?
We have had the same issue and stopped our attempts to use JenkinsX - until there is a fixed version of kubernetes in EKS deployable.

**Closed** 2019-08-02 22:07 UTC
Labels: lifecycle/rotten
